### PR TITLE
Update plots for base

### PR DESCRIPTION
**Pull request by parkerburchett**

### CODE REVIEW

**Comment by parkerburchett** [comment]
image

base ETH start date should be updated

**Comment by parkerburchett** [comment]
all the rebalance events bars are twice as tall for some reason

image

**Comment by parkerburchett** [comment]
image
Debt reporting ETH sent to autopool scale is off

**Comment by parkerburchett** [comment]
image
the bars here are too thin

image

**Comment by parkerburchett** [comment]
image

gas costs are not correct in the previous 7 days

**Comment by parkerburchett** [comment]
image
Only has eth mainnet, not Base

**Comment by parkerburchett** [comment]
image
autoLRT nav incorrect

image

**Review by ahuja88 — APPROVED** [review]

**Pull request merged**
